# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayingWithZXing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlayingWithZXing

        pod 'ZXingObjC', '~> 3.2.1'



  target 'PlayingWithZXingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlayingWithZXingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
